### ISSUE TITLE
Wiring

### ISSUE THREAD

**Issue by marko-pi** [JMW95/pyST7920#1]
Could you provide wiring diagram?

I am also concerned by the fact that (according to sellers) ST7920 is 5V logic and Raspberry Pi is 3.3V logic.  I am aware that perhaps ST7920 could be tweaked to 3.3V (by e.g. jumpers), but I cannot find any documentation on this.

**Comment by Akintos** [comment]
I know this is an old issue, but for sake of information, I'll leave a comment.
There are some ST7920 GLCD with 3.3v operating voltage (ex. http://www.waveshare.com/lcd12864-st-3.3v-blue.htm)
For wiring, check [this image](http://cfile8.uf.tistory.com/image/21410838578E2FB51F6CA8). Connect pin 5 with GPIO9(SPI0_MISO) and pin 6 with GPIO11(SPI0_SCLK).

**Comment by edmundhei** [comment]
Hi is it possible provide wiring to raspberry pi 3?

**Comment by OnkarTanwade** [comment]
my graphical LCD does not have cs1 and cs2 pins what should I do. Please help me I am stuck over their.

**Comment by stephiscoding** [comment]
once again, just for any people in the future who are wondering, the wiring is the same for all 40 pin raspberry pis (anything that isn't a first generation model B or A essentially), and if your pins do not match it is likely that your LCD driver is different and this library will not work. it could also be just different pin names, so check with your manufacturer.

**Comment by Stephanowicz** [comment]
FYI - I got it working on **RPI 4** with the following mods/settings:

in **st7920.py** @line 11 I had to reduce the bus-speed to 1200000:
`		self.spi.max_speed_hz = 1200000 # set SPI clock to 1.2MHz, up from 125kHz
`

I followed this connection table:

![image](https://user-images.githubusercontent.com/12005507/169667413-9c74753c-fb7d-4d79-8179-f28ebd518126.png)

Pin 24 - SPI CE0 didn't work, but Pin 26 - SPI CE1 did... (I didn't investigate further)
(btw. as mentioned before - CS is the RS pin of the LCD)

Hope this helps.

Cheers, Stephan

**Comment by marko-pi** [comment]
I solved my problem by writing my own code. You can find it along with the wiring here: https://www.pinteric.com/displays.html#st2

I think this closes this issue.

**Comment by Marc2629** [comment]
> FYI - I got it working on **RPI 4** with the following mods/settings:
> 
> in **st7920.py** @line 11 I had to reduce the bus-speed to 1200000: ` self.spi.max_speed_hz = 1200000 # set SPI clock to 1.2MHz, up from 125kHz `
> 
> I followed this connection table:
> 
> ![image](https://user-images.githubusercontent.com/12005507/169667413-9c74753c-fb7d-4d79-8179-f28ebd518126.png)
> 
> Pin 24 - SPI CE0 didn't work, but Pin 26 - SPI CE1 did... (I didn't investigate further) (btw. as mentioned before - CS is the RS pin of the LCD)
> 
> Hope this helps.
> 
> Cheers, Stephan

Thanks for this!!! No idea why the other pin was not working.... but it after several evenings (yes really!) it's finally working!

*edit* I spent 5 mins looking into this and since the main script initializes self.spi.open(0,0) selecting CE0, it seems odd that swapping the pins from CE0 to CE1 worked? Since CE0 should have been explicitly selected...
